name: Deployment Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

# Cuando se ejecuta?
on:
  push:
    branches:
      - master

# Trabajos por hacer
jobs:
  #nombre
  deploy:
    # sistema operativo
    runs-on: windows-latest
    steps:
      # Se trae el último commit a la máquina
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run eslint
